image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install dependencies
    command: yarn install


vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - mochisann.create-react-component-with-storybook-and-testfile
    - dsznajder.es7-react-js-snippets
    - dbaeumer.vscode-eslint
    - mhutchie.git-graph
    - eamodio.gitlens
    - andys8.jest-snippets
    - bierner.jsdoc-markdown-highlighting
    - esbenp.prettier-vscode
    - wallabyjs.quokka-vscode
    - equimper.react-native-react-redux
    - devexpress.rushcore
    - devexpress.rushsnippets
    - tabnine.tabnine-vscode
    - chakrounanas.turbo-console-log
    - wallabyjs.wallaby-vscode
    - hbenl.vscode-test-explorer
